/**
 * Property-Based Tests for JWEEncryptor Module
 * 
 * Feature: lambda-encryption-decryption, Property 2: Formato y Algoritmos JWE
 * 
 * Uses fast-check to verify that all tokens generated by Lambda_Encriptacion
 * follow the JWE standard format and use the correct algorithms.
 * 
 * Validates: Requirements 1.4, 1.5, 5.3, 5.4, 8.1
 */

import * as fc from 'fast-check';
import { JWEEncryptor } from './JWEEncryptor';
import * as jose from 'jose';

describe('JWEEncryptor Property-Based Tests', () => {
  let validPublicKey: jose.JWK;
  let encryptor: JWEEncryptor;

  beforeAll(async () => {
    // Generate a test RSA key pair for testing
    const { publicKey } = await jose.generateKeyPair('RSA-OAEP-256', {
      modulusLength: 2048
    });

    // Export public key to JWK format
    validPublicKey = await jose.exportJWK(publicKey);
    validPublicKey.use = 'enc';
    validPublicKey.kid = 'test-key-property';
  });

  beforeEach(() => {
    encryptor = new JWEEncryptor(validPublicKey);
  });

  // ============================================================================
  // Custom Generators
  // ============================================================================

  /**
   * Generator for valid payloads (any JSON-serializable data)
   */
  const arbitraryValidPayload = (): fc.Arbitrary<any> => {
    return fc.oneof(
      // Simple objects
      fc.record({
        userId: fc.string(),
        email: fc.emailAddress(),
        data: fc.anything()
      }),
      // Nested objects
      fc.record({
        user: fc.record({
          id: fc.uuid(),
          name: fc.string(),
          profile: fc.record({
            age: fc.integer({ min: 0, max: 120 }),
            country: fc.string()
          })
        }),
        timestamp: fc.date().map(d => d.toISOString())
      }),
      // Arrays
      fc.array(fc.anything(), { minLength: 1, maxLength: 10 }),
      // Mixed types
      fc.record({
        string: fc.string(),
        number: fc.integer(),
        boolean: fc.boolean(),
        array: fc.array(fc.integer()),
        nested: fc.record({
          key: fc.string()
        })
      }),
      // Primitives
      fc.string(),
      fc.integer(),
      fc.boolean(),
      fc.constant(null),
      // Empty structures
      fc.constant({}),
      fc.constant([])
    );
  };

  /**
   * Generator for payloads with special characters
   */
  const arbitraryPayloadWithSpecialChars = (): fc.Arbitrary<any> => {
    return fc.record({
      text: fc.oneof(
        fc.constant('Special chars: áéíóú ñ'),
        fc.constant('中文 日本語 한글'),
        fc.constant('🚀 emoji 🎉 test'),
        fc.constant('!@#$%^&*()_+-=[]{}|;:,.<>?')
      ),
      data: fc.anything()
    });
  };

  /**
   * Generator for large payloads (up to 1MB)
   */
  const arbitraryLargePayload = (): fc.Arbitrary<any> => {
    return fc.integer({ min: 100000, max: 1000000 }).map(size => ({
      data: 'x'.repeat(size),
      metadata: {
        size,
        timestamp: new Date().toISOString()
      }
    }));
  };

  // ============================================================================
  // Property 2: Formato y Algoritmos JWE
  // **Validates: Requirements 1.4, 1.5, 5.3, 5.4, 8.1**
  // ============================================================================

  describe('Property 2: Formato y Algoritmos JWE', () => {
    /**
     * For any valid payload encrypted by Lambda_Encriptacion, the resulting JWE token MUST:
     * - Have compact JWE format (5 parts separated by dots)
     * - Contain in its protected header: "alg": "RSA-OAEP-256"
     * - Contain in its protected header: "enc": "A256GCM"
     * - Be compliant with RFC 7516
     */

    test('all encrypted tokens have compact JWE format with exactly 5 parts', async () => {
      await fc.assert(
        fc.asyncProperty(
          arbitraryValidPayload(),
          async (payload) => {
            const token = await encryptor.encrypt(payload);
            
            // Requirement 5.3: Token must have compact JWE format (5 parts separated by dots)
            const parts = token.split('.');
            expect(parts).toHaveLength(5);
            
            // Each part must be non-empty
            parts.forEach((part) => {
              expect(part.length).toBeGreaterThan(0);
              expect(part).not.toBe('');
            });
          }
        ),
        { numRuns: 100 }
      );
    });

    test('all encrypted tokens use RSA-OAEP-256 algorithm for key encryption', async () => {
      await fc.assert(
        fc.asyncProperty(
          arbitraryValidPayload(),
          async (payload) => {
            const token = await encryptor.encrypt(payload);
            
            // Decode the protected header (first part of JWE)
            const parts = token.split('.');
            const protectedHeaderB64 = parts[0]!;
            
            // Decode base64url to JSON
            const protectedHeaderJson = Buffer.from(
              protectedHeaderB64
                .replace(/-/g, '+')
                .replace(/_/g, '/'),
              'base64'
            ).toString('utf8');
            
            const protectedHeader = JSON.parse(protectedHeaderJson);
            
            // Requirement 1.4: Must use RSA-OAEP-256 for key encryption
            // Requirement 5.4: Token must use expected algorithm
            expect(protectedHeader).toHaveProperty('alg');
            expect(protectedHeader.alg).toBe('RSA-OAEP-256');
          }
        ),
        { numRuns: 100 }
      );
    });

    test('all encrypted tokens use A256GCM algorithm for content encryption', async () => {
      await fc.assert(
        fc.asyncProperty(
          arbitraryValidPayload(),
          async (payload) => {
            const token = await encryptor.encrypt(payload);
            
            // Decode the protected header (first part of JWE)
            const parts = token.split('.');
            const protectedHeaderB64 = parts[0]!;
            
            // Decode base64url to JSON
            const protectedHeaderJson = Buffer.from(
              protectedHeaderB64
                .replace(/-/g, '+')
                .replace(/_/g, '/'),
              'base64'
            ).toString('utf8');
            
            const protectedHeader = JSON.parse(protectedHeaderJson);
            
            // Requirement 1.5: Must use A256GCM for content encryption
            // Requirement 5.4: Token must use expected algorithm
            expect(protectedHeader).toHaveProperty('enc');
            expect(protectedHeader.enc).toBe('A256GCM');
          }
        ),
        { numRuns: 100 }
      );
    });

    test('all encrypted tokens have both required algorithms in protected header', async () => {
      await fc.assert(
        fc.asyncProperty(
          arbitraryValidPayload(),
          async (payload) => {
            const token = await encryptor.encrypt(payload);
            
            // Decode the protected header
            const parts = token.split('.');
            const protectedHeaderB64 = parts[0]!;
            const protectedHeaderJson = Buffer.from(
              protectedHeaderB64
                .replace(/-/g, '+')
                .replace(/_/g, '/'),
              'base64'
            ).toString('utf8');
            
            const protectedHeader = JSON.parse(protectedHeaderJson);
            
            // Requirements 1.4, 1.5, 5.4: Both algorithms must be present and correct
            expect(protectedHeader.alg).toBe('RSA-OAEP-256');
            expect(protectedHeader.enc).toBe('A256GCM');
          }
        ),
        { numRuns: 100 }
      );
    });

    test('all token parts are valid base64url encoded strings', async () => {
      await fc.assert(
        fc.asyncProperty(
          arbitraryValidPayload(),
          async (payload) => {
            const token = await encryptor.encrypt(payload);
            const parts = token.split('.');
            
            // Requirement 8.1: RFC 7516 compliance - all parts must be base64url encoded
            // Base64url uses: A-Z, a-z, 0-9, -, _ (no padding)
            const base64urlPattern = /^[A-Za-z0-9_-]+$/;
            
            parts.forEach((part) => {
              expect(part).toMatch(base64urlPattern);
            });
          }
        ),
        { numRuns: 100 }
      );
    });

    test('protected header is valid JSON when decoded', async () => {
      await fc.assert(
        fc.asyncProperty(
          arbitraryValidPayload(),
          async (payload) => {
            const token = await encryptor.encrypt(payload);
            const parts = token.split('.');
            const protectedHeaderB64 = parts[0]!;
            
            // Requirement 8.1: RFC 7516 compliance - header must be valid JSON
            const protectedHeaderJson = Buffer.from(
              protectedHeaderB64
                .replace(/-/g, '+')
                .replace(/_/g, '/'),
              'base64'
            ).toString('utf8');
            
            // Should not throw when parsing
            expect(() => JSON.parse(protectedHeaderJson)).not.toThrow();
            
            const protectedHeader = JSON.parse(protectedHeaderJson);
            
            // Should be an object
            expect(typeof protectedHeader).toBe('object');
            expect(protectedHeader).not.toBeNull();
          }
        ),
        { numRuns: 100 }
      );
    });

    test('tokens with special characters maintain correct format', async () => {
      await fc.assert(
        fc.asyncProperty(
          arbitraryPayloadWithSpecialChars(),
          async (payload) => {
            const token = await encryptor.encrypt(payload);
            
            // Format validation
            const parts = token.split('.');
            expect(parts).toHaveLength(5);
            
            // Algorithm validation
            const protectedHeaderB64 = parts[0]!;
            const protectedHeaderJson = Buffer.from(
              protectedHeaderB64
                .replace(/-/g, '+')
                .replace(/_/g, '/'),
              'base64'
            ).toString('utf8');
            
            const protectedHeader = JSON.parse(protectedHeaderJson);
            expect(protectedHeader.alg).toBe('RSA-OAEP-256');
            expect(protectedHeader.enc).toBe('A256GCM');
          }
        ),
        { numRuns: 100 }
      );
    });

    test('large payloads produce valid JWE tokens', async () => {
      await fc.assert(
        fc.asyncProperty(
          arbitraryLargePayload(),
          async (payload) => {
            const token = await encryptor.encrypt(payload);
            
            // Format validation
            const parts = token.split('.');
            expect(parts).toHaveLength(5);
            
            // Algorithm validation
            const protectedHeaderB64 = parts[0]!;
            const protectedHeaderJson = Buffer.from(
              protectedHeaderB64
                .replace(/-/g, '+')
                .replace(/_/g, '/'),
              'base64'
            ).toString('utf8');
            
            const protectedHeader = JSON.parse(protectedHeaderJson);
            expect(protectedHeader.alg).toBe('RSA-OAEP-256');
            expect(protectedHeader.enc).toBe('A256GCM');
          }
        ),
        { numRuns: 50 } // Fewer runs for large payloads to avoid timeout
      );
    });

    test('same payload produces different tokens (due to random IV)', async () => {
      await fc.assert(
        fc.asyncProperty(
          arbitraryValidPayload(),
          async (payload) => {
            // Encrypt the same payload twice
            const token1 = await encryptor.encrypt(payload);
            const token2 = await encryptor.encrypt(payload);
            
            // Tokens should be different (due to random initialization vector)
            expect(token1).not.toBe(token2);
            
            // But both should have valid format
            expect(token1.split('.')).toHaveLength(5);
            expect(token2.split('.')).toHaveLength(5);
            
            // And both should have correct algorithms
            const verifyAlgorithms = (token: string) => {
              const parts = token.split('.');
              const protectedHeaderB64 = parts[0]!;
              const protectedHeaderJson = Buffer.from(
                protectedHeaderB64
                  .replace(/-/g, '+')
                  .replace(/_/g, '/'),
                'base64'
              ).toString('utf8');
              const protectedHeader = JSON.parse(protectedHeaderJson);
              return protectedHeader.alg === 'RSA-OAEP-256' && 
                     protectedHeader.enc === 'A256GCM';
            };
            
            expect(verifyAlgorithms(token1)).toBe(true);
            expect(verifyAlgorithms(token2)).toBe(true);
          }
        ),
        { numRuns: 100 }
      );
    });

    test('encrypted tokens are RFC 7516 compliant (can be parsed by jose library)', async () => {
      await fc.assert(
        fc.asyncProperty(
          arbitraryValidPayload(),
          async (payload) => {
            const token = await encryptor.encrypt(payload);
            
            // Requirement 8.1: Tokens must be RFC 7516 compliant
            // Verify by attempting to parse with jose library
            // This validates the token structure is correct
            
            // Extract the protected header using jose's decodeProtectedHeader
            expect(() => jose.decodeProtectedHeader(token)).not.toThrow();
            
            const header = jose.decodeProtectedHeader(token);
            
            // Verify header structure
            expect(header).toHaveProperty('alg');
            expect(header).toHaveProperty('enc');
            expect(header.alg).toBe('RSA-OAEP-256');
            expect(header.enc).toBe('A256GCM');
          }
        ),
        { numRuns: 100 }
      );
    });

    test('all five JWE parts are present and non-empty', async () => {
      await fc.assert(
        fc.asyncProperty(
          arbitraryValidPayload(),
          async (payload) => {
            const token = await encryptor.encrypt(payload);
            const parts = token.split('.');
            
            // Requirement 5.3: JWE compact format has 5 parts
            // RFC 7516: Protected Header, Encrypted Key, IV, Ciphertext, Authentication Tag
            expect(parts).toHaveLength(5);
            
            const [protectedHeader, encryptedKey, iv, ciphertext, authTag] = parts;
            
            // All parts must be non-empty
            expect(protectedHeader).toBeTruthy();
            expect(protectedHeader!.length).toBeGreaterThan(0);
            
            expect(encryptedKey).toBeTruthy();
            expect(encryptedKey!.length).toBeGreaterThan(0);
            
            expect(iv).toBeTruthy();
            expect(iv!.length).toBeGreaterThan(0);
            
            expect(ciphertext).toBeTruthy();
            expect(ciphertext!.length).toBeGreaterThan(0);
            
            expect(authTag).toBeTruthy();
            expect(authTag!.length).toBeGreaterThan(0);
          }
        ),
        { numRuns: 100 }
      );
    });

    test('encryption never throws for valid payloads', async () => {
      await fc.assert(
        fc.asyncProperty(
          arbitraryValidPayload(),
          async (payload) => {
            // Encryption should never throw for valid payloads
            await expect(encryptor.encrypt(payload)).resolves.toBeDefined();
            
            const token = await encryptor.encrypt(payload);
            
            // Token should be a non-empty string
            expect(typeof token).toBe('string');
            expect(token.length).toBeGreaterThan(0);
          }
        ),
        { numRuns: 100 }
      );
    });

    test('token format is consistent across different payload types', async () => {
      await fc.assert(
        fc.asyncProperty(
          fc.oneof(
            fc.record({ key: fc.string() }),
            fc.array(fc.integer()),
            fc.string(),
            fc.integer(),
            fc.boolean(),
            fc.constant(null)
          ),
          async (payload) => {
            const token = await encryptor.encrypt(payload);
            
            // All payload types should produce tokens with same format
            const parts = token.split('.');
            expect(parts).toHaveLength(5);
            
            // All should use same algorithms
            const protectedHeaderB64 = parts[0]!;
            const protectedHeaderJson = Buffer.from(
              protectedHeaderB64
                .replace(/-/g, '+')
                .replace(/_/g, '/'),
              'base64'
            ).toString('utf8');
            
            const protectedHeader = JSON.parse(protectedHeaderJson);
            expect(protectedHeader.alg).toBe('RSA-OAEP-256');
            expect(protectedHeader.enc).toBe('A256GCM');
          }
        ),
        { numRuns: 100 }
      );
    });

    test('protected header contains only expected fields', async () => {
      await fc.assert(
        fc.asyncProperty(
          arbitraryValidPayload(),
          async (payload) => {
            const token = await encryptor.encrypt(payload);
            
            // Decode protected header
            const parts = token.split('.');
            const protectedHeaderB64 = parts[0]!;
            const protectedHeaderJson = Buffer.from(
              protectedHeaderB64
                .replace(/-/g, '+')
                .replace(/_/g, '/'),
              'base64'
            ).toString('utf8');
            
            const protectedHeader = JSON.parse(protectedHeaderJson);
            
            // Must have alg and enc
            expect(protectedHeader).toHaveProperty('alg');
            expect(protectedHeader).toHaveProperty('enc');
            
            // Values must be correct
            expect(protectedHeader.alg).toBe('RSA-OAEP-256');
            expect(protectedHeader.enc).toBe('A256GCM');
            
            // Should not have unexpected critical fields that would break decryption
            // (Optional fields like kid, typ are allowed by RFC 7516)
          }
        ),
        { numRuns: 100 }
      );
    });
  });
});
